name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: jaanuk/sp-project:latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and test it
      run: docker build . --file Dockerfile --tag ${{env.IMAGE_NAME}}
    
    - name: Run the conatainer
      run: docker run -d -p 5000:5000 ${{env.IMAGE_NAME}}

    - name: Log into Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{env.IMAGE_NAME}}
